language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - python ./mysite/manage.py migrate
before_script:
  - cd ./mysite/
script:
  - black --check blogging mysite polling
  - python manage.py test